project:
  type: book

book:
  title: "Welcome to the Command Line"
  author: "Mick McQuaid"
  date: today
  chapters:
    - index.qmd
    - macSetupIntelFull.qmd
    - macSetupIntelMinimal.qmd
    - macSetupM1Full.qmd
    - macSetupM1Minimal.qmd
    - whyCLI.qmd
    - whyVIM.qmd
    - unixNature.qmd
    - man.qmd
    - terminal.qmd
    - macGeneral/iTerm.qmd
    - bash.qmd
    - tmux.qmd
    - bearings.qmd
    - fileIO.qmd
    - fileManipulation.qmd
    - textManipulation.qmd
    - vim.qmd
    - macGeneral/macDotFiles.qmd
    - macGeneral/macVim.qmd
    - references.qmd
format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 350px
bibliography: master.bib
mainfont: Tex Gyre Schola
monofont: JetBrainsMono Nerd Font
mathfont: Tex Gyre Schola Math

